//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCMS_Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyCMSEntities : DbContext
    {
        public EasyCMSEntities()
            : base("name=EasyCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ES_Menu> ES_Menu { get; set; }
        public virtual DbSet<ES_Menu_Role> ES_Menu_Role { get; set; }
        public virtual DbSet<ES_Role> ES_Role { get; set; }
        public virtual DbSet<ES_User> ES_User { get; set; }
    }
}
